### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mikaturunen**
Updated the README.md a bit. In all fairness, added of no real value but made it just crystal clear on how to get things running - the readme kind of made it understood that just running "redom" would start the server with magic.

### CODE REVIEW

**Comment by pakastin** [comment]
Actually redom-cli should already call `npm install` and I recall there's notice to call `npm start` when you go through `redom-cli`

**Comment by pakastin** [comment]
https://github.com/pakastin/redom-cli/blob/master/bin/redom.js

**Comment by mikaturunen** [comment]
well that's confusing as out of the box for me it did neither and thus the confusion with the `README.md`. Looking into it. We can safely go with the assumption that the problem is between the chair and the desk on this one.

**Comment by pakastin** [comment]
What OS do you have? There's been some issues with Windows..

**Comment by mikaturunen** [comment]
OSX Sierra. On top of that it was lacking the index.styl file too, it seems.

**Comment by pakastin** [comment]
Oh, that's weird since I just added it. Do you have an old version of `redom-cli`?

Here's what happens after the install:
https://github.com/pakastin/redom-cli/blob/master/bin/redom.js#L159

There could be some notification about following the instructions of `redom-cli` or similar before opening the browser..

**Comment by pakastin** [comment]
I will take a look if there's some issue. I haven't use the generator that much lately..

**Comment by mikaturunen** [comment]
To be fair, I completely understand the state of the generators really - I just bootstrapped my extension development with this - got it to working with about 30 seconds of wondering how it works so nothing serious really. 

All in all, thanks for the work. Seems like pleasant little beast to work with.

**Comment by pakastin** [comment]
Ok, great! 😎👍

**Comment by pakastin** [comment]
Btw. `npm start` only starts the server, but `npm run dev` also starts to watch files 😉

**Comment by pakastin** [comment]
It seems I forgot to call `npm publish` after 0.4.0 – it's now updated:
https://www.npmjs.com/package/redom-cli

`npm update` should do the trick (make sure it installs 0.4.0) ;)

**Pull request merged**
